import { NextResponse } from "next/server";
import { getSupabaseUserFromRequest, getSupabaseServerClient } from "@/lib/supabase/server";
import { ERRORS } from "@/lib/api/helpers";
import { checkRateLimit, RATE_LIMITS } from "@/lib/api/rate-limit";
import { getYouTubeTranscript } from "@/lib/integrations/youtube";
import { chunkText } from "@/lib/rag/chunk";
import { embedBatchSafe } from "@/lib/rag/embed";
import { createLogger } from "@/lib/logger";

const log = createLogger("api/integrations/youtube");

export async function POST(request: Request) {
  // 1. Auth
  const { user } = await getSupabaseUserFromRequest(request);
  if (!user) return ERRORS.UNAUTHORIZED();

  // 2. Rate limit
  const rl = await checkRateLimit(user.id, RATE_LIMITS.integration);
  if (!rl.allowed) return rl.response;

  // 3. Input validation
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return ERRORS.INVALID_INPUT("Тело запроса должно быть валидным JSON.");
  }

  const { url, title } = body as Record<string, unknown>;

  if (!url || typeof url !== "string") {
    return ERRORS.INVALID_INPUT("Поле 'url' обязательно (ссылка на YouTube видео).");
  }

  const documentTitle =
    typeof title === "string" && title.trim().length > 0
      ? title.trim()
      : `YouTube: ${url.slice(0, 60)}`;

  // 4. Fetch transcript
  let transcriptResult: Awaited<ReturnType<typeof getYouTubeTranscript>>;
  try {
    transcriptResult = await getYouTubeTranscript(url);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Ошибка при получении субтитров.";
    log.warn("Transcript fetch failed", { userId: user.id, url, error: message });
    return NextResponse.json({ ok: false, error: "transcript_error", message }, { status: 422 });
  }

  const { transcript, videoId, language, isAutoGenerated } = transcriptResult;

  // 5. Create document record
  const supabase = getSupabaseServerClient();
  const documentId = crypto.randomUUID();

  const { error: insertError } = await supabase.from("documents").insert({
    id: documentId,
    user_id: user.id,
    title: documentTitle,
    file_path: `youtube/${videoId}`,
    mime_type: "text/plain",
    source_type: "youtube",
    processing_status: "processing"
  });

  if (insertError) {
    log.error("Document insert failed", insertError, { userId: user.id, videoId });
    return ERRORS.INTERNAL("Не удалось создать запись документа.");
  }

  // 6. Chunk + embed + store (inline — transcripts are small enough)
  const chunks = chunkText(transcript);

  if (chunks.length === 0) {
    await supabase
      .from("documents")
      .update({ processing_status: "failed", error_message: "Пустой транскрипт." })
      .eq("id", documentId);

    return NextResponse.json(
      { ok: false, error: "empty_transcript", message: "Транскрипт пустой." },
      { status: 422 }
    );
  }

  try {
    const embeddings = await embedBatchSafe(chunks);
    const chunkRows = chunks.map((chunk, index) => ({
      id: crypto.randomUUID(),
      document_id: documentId,
      chunk_text: chunk,
      chunk_index: index,
      embedding: embeddings[index],
      token_count: Math.max(1, Math.ceil(chunk.length / 4))
    }));

    const { error: chunksError } = await supabase.from("document_chunks").insert(chunkRows);
    if (chunksError) throw chunksError;

    await supabase
      .from("documents")
      .update({ processing_status: "ready" })
      .eq("id", documentId);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Ошибка embedding.";
    log.error("Embedding failed", err, { documentId });
    await supabase
      .from("documents")
      .update({ processing_status: "failed", error_message: message })
      .eq("id", documentId);
    return ERRORS.INTERNAL("Не удалось создать embeddings для транскрипта.");
  }

  log.info("YouTube transcript imported", {
    userId: user.id,
    videoId,
    documentId,
    chunks: chunks.length,
    language,
    isAutoGenerated
  });

  return NextResponse.json({
    ok: true,
    documentId,
    videoId,
    language,
    isAutoGenerated,
    chunks: chunks.length,
    message: `Транскрипт успешно импортирован (${chunks.length} фрагментов, язык: ${language}).`
  });
}
