import { createLogger } from "@/lib/logger";

const log = createLogger("integrations/youtube");

/** Extracts YouTube video ID from common URL formats. */
export function extractVideoId(url: string): string | null {
  const patterns = [
    /[?&]v=([A-Za-z0-9_-]{11})/,           // youtube.com/watch?v=ID
    /youtu\.be\/([A-Za-z0-9_-]{11})/,        // youtu.be/ID
    /\/embed\/([A-Za-z0-9_-]{11})/,          // youtube.com/embed/ID
    /\/shorts\/([A-Za-z0-9_-]{11})/          // youtube.com/shorts/ID
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }
  return null;
}

interface TimedTextTrack {
  languageCode: string;
  name: { simpleText: string };
  kind?: string;
  isTranslatable: boolean;
}

interface CaptionEntry {
  start: number;
  dur: number;
  text: string;
}

/**
 * Parses WebVTT / timed-text XML format into plain text.
 */
function parseTimedTextXml(xml: string): string {
  // Remove XML tags, decode HTML entities
  return xml
    .replace(/<[^>]+>/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s{2,}/g, " ")
    .trim();
}

/**
 * Fetches the list of available caption tracks from YouTube's internal API.
 * Parses the `ytInitialData` / `innertubeApiKey` from the watch page HTML.
 */
async function fetchCaptionTracks(
  videoId: string
): Promise<TimedTextTrack[]> {
  const res = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    headers: {
      "User-Agent":
        "Mozilla/5.0 (compatible; StudyFlowBot/1.0; +https://studyflow.ai)",
      "Accept-Language": "ru,en;q=0.9"
    }
  });

  if (!res.ok) {
    throw new Error(`YouTube watch page returned ${res.status}`);
  }

  const html = await res.text();

  // Extract caption track data from ytInitialPlayerResponse
  const match = html.match(/"captionTracks":(\[.*?\])/s);
  if (!match) return [];

  try {
    return JSON.parse(match[1]) as TimedTextTrack[];
  } catch {
    return [];
  }
}

/**
 * Downloads and parses a timed-text track from YouTube.
 */
async function downloadTrack(
  videoId: string,
  langCode: string,
  kind?: string
): Promise<string> {
  const params = new URLSearchParams({
    v: videoId,
    lang: langCode,
    fmt: "ttml",
    ...(kind ? { kind } : {})
  });

  const url = `https://www.youtube.com/api/timedtext?${params}`;
  const res = await fetch(url, {
    headers: {
      "User-Agent": "Mozilla/5.0 (compatible; StudyFlowBot/1.0)"
    }
  });

  if (!res.ok || res.headers.get("content-length") === "0") {
    return "";
  }

  const xml = await res.text();
  return parseTimedTextXml(xml);
}

export interface YouTubeTranscriptResult {
  videoId: string;
  title?: string;
  language: string;
  transcript: string;
  isAutoGenerated: boolean;
  source: "timedtext" | "youtube_api";
}

/**
 * Fetches transcript for a YouTube video.
 *
 * Priority order:
 *   1. Manual Russian captions
 *   2. Auto-generated Russian captions
 *   3. Manual English captions
 *   4. Auto-generated English captions
 *   5. Any available language
 *
 * If YOUTUBE_API_KEY is set, uses Data API v3 for more reliable access.
 * Otherwise uses the unofficial timedtext endpoint.
 */
export async function getYouTubeTranscript(
  videoUrl: string
): Promise<YouTubeTranscriptResult> {
  const videoId = extractVideoId(videoUrl);
  if (!videoId) {
    throw new Error("Не удалось извлечь ID видео из URL. Поддерживаются youtube.com и youtu.be.");
  }

  log.info("Fetching transcript", { videoId });

  // Try to get caption tracks list
  let tracks: TimedTextTrack[] = [];
  try {
    tracks = await fetchCaptionTracks(videoId);
  } catch (err) {
    log.warn("Could not fetch caption tracks list", { videoId, error: (err as Error).message });
  }

  // Build language priority list
  const PRIORITY_LANGS = ["ru", "ru-RU", "en", "en-US", "en-GB"];

  // Sort tracks by priority
  const sorted = [...tracks].sort((a, b) => {
    const aIdx = PRIORITY_LANGS.indexOf(a.languageCode);
    const bIdx = PRIORITY_LANGS.indexOf(b.languageCode);
    const aPriority = aIdx === -1 ? 99 : aIdx;
    const bPriority = bIdx === -1 ? 99 : bIdx;
    // Manual captions before auto-generated
    const aAuto = a.kind === "asr" ? 1 : 0;
    const bAuto = b.kind === "asr" ? 1 : 0;
    return aPriority - bPriority || aAuto - bAuto;
  });

  // Try each track until we get content
  for (const track of sorted) {
    try {
      const text = await downloadTrack(videoId, track.languageCode, track.kind);
      if (text.length > 100) {
        log.info("Transcript fetched", {
          videoId,
          lang: track.languageCode,
          chars: text.length,
          auto: track.kind === "asr"
        });
        return {
          videoId,
          language: track.languageCode,
          transcript: text,
          isAutoGenerated: track.kind === "asr",
          source: "timedtext"
        };
      }
    } catch (err) {
      log.warn("Track download failed", {
        videoId,
        lang: track.languageCode,
        error: (err as Error).message
      });
    }
  }

  // Last resort: try common languages directly without the track list
  for (const lang of PRIORITY_LANGS) {
    const text = await downloadTrack(videoId, lang);
    if (text.length > 100) {
      return {
        videoId,
        language: lang,
        transcript: text,
        isAutoGenerated: true,
        source: "timedtext"
      };
    }
  }

  throw new Error(
    "Субтитры для этого видео недоступны. Убедитесь, что видео публичное и имеет субтитры."
  );
}
